language: java
dist: trusty

jdk:
  - oraclejdk8
  - openjdk11
  - openjdk12
  - openjdk14

cache:
  directories:
    - .autoconf
    - $HOME/.m2
before_install:
   - "export M2_HOME=/usr/local/maven"